env:
  browser: true
  es6: true
extends: [
    'eslint:recommended',
    'plugin:react/recommended'
]
parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
