export const ADD_COLOR_FILTER = "ADD_COLOR_FILTER";
export const ADD_CATEGORY_FILTER = "ADD_CATEGORY_FILTER";
export const REMOVE_COLOR_FILTER = "REMOVE_COLOR_FILTER";
export const REMOVE_CATEGORY_FILTER = "REMOVE_CATEGORY_FILTER";
